spring.application.name=demo
# Enable Docker Compose support
spring.docker.compose.enabled=true

# Point to file (since it's in the project root)
spring.docker.compose.file=./compose.yaml

# Tell Hibernate to automatically create database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Optional: Give Kafka a moment to start up
spring.docker.compose.readiness.tcp.connect-timeout=20s

server.port = 8081

#Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Deserialize
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.DTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.demo.DTO.CreateOrderRequest

# Database Connection Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Show details for all health indicators (DB, Kafka, Disk, etc.)
# Make sure there are no spaces after the equals sign
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#Disable kafka on remote deployment.
#Docker will auto create a local kafka container, but railway has no service support directly
spring.kafka.listener.auto-startup=false
